// Copyright 2026 Andrew Yates
// SPDX-License-Identifier: Apache-2.0 OR MIT
// Author: Andrew Yates <andrewyates.name@gmail.com>

// Copyright Kani Contributors
// SPDX-License-Identifier: Apache-2.0 OR MIT
//! Kani function classification enums.
//!
//! There are three categories of special Kani functions:
//!    1. **Intrinsics**: MIR bodies generated during compilation (require type knowledge).
//!    2. **Models**: Functions modeling specific runtime behavior for Kani instrumentation.
//!    3. **Hooks**: Backend-specific logic generated during codegen.
//!
//! These functions are marked with `kanitool::fn_marker` attributes. The marker
//! value contains "Intrinsic", "Model", or "Hook" suffix indicating category.
//!
//! Extracted from `trust_mc-compiler/src/kani_middle/kani_functions.rs` (Part of #2997).

use std::str::FromStr;
use strum_macros::{EnumIter, EnumString, IntoStaticStr};

#[derive(Debug, Copy, Clone, Eq, PartialEq, Hash)]
pub enum KaniFunction {
    Model(KaniModel),
    Intrinsic(KaniIntrinsic),
    Hook(KaniHook),
}

/// Kani intrinsics are functions generated by the compiler.
///
/// These functions usually depend on information that require extra knowledge about the type
/// or extra Kani instrumentation.
#[derive(Debug, Copy, Clone, Eq, PartialEq, IntoStaticStr, EnumIter, EnumString, Hash)]
pub enum KaniIntrinsic {
    #[strum(serialize = "AnyModifiesIntrinsic")]
    AnyModifies,
    #[strum(serialize = "CheckedAlignOfIntrinsic")]
    CheckedAlignOf,
    #[strum(serialize = "CheckedSizeOfIntrinsic")]
    CheckedSizeOf,
    #[strum(serialize = "AutomaticHarnessIntrinsic")]
    AutomaticHarness,
    /// Checks if a float value can be converted to an integer without overflow.
    /// Returns true if the value after truncation is in range of the target Int type.
    /// Part of #1369: Converted from hook to intrinsic for uniform semantics.
    #[strum(serialize = "FloatToIntInRangeIntrinsic")]
    FloatToIntInRange,
    #[strum(serialize = "IsInitializedIntrinsic")]
    IsInitialized,
    #[strum(serialize = "ValidValueIntrinsic")]
    ValidValue,
    #[strum(serialize = "WriteAnyIntrinsic")]
    WriteAny,
}

/// Kani models are Rust functions that model some runtime behavior used by Kani instrumentation.
#[derive(Debug, Copy, Clone, Eq, PartialEq, IntoStaticStr, EnumIter, EnumString, Hash)]
pub enum KaniModel {
    #[strum(serialize = "AlignOfDynObjectModel")]
    AlignOfDynObject,
    #[strum(serialize = "AlignOfValRawModel")]
    AlignOfVal,
    #[strum(serialize = "AnyModel")]
    Any,
    #[strum(serialize = "CopyInitStateModel")]
    CopyInitState,
    #[strum(serialize = "CopyInitStateSingleModel")]
    CopyInitStateSingle,
    #[strum(serialize = "LoadArgumentModel")]
    LoadArgument,
    #[strum(serialize = "InitializeMemoryInitializationStateModel")]
    InitializeMemoryInitializationState,
    #[strum(serialize = "IsPtrInitializedModel")]
    IsPtrInitialized,
    #[strum(serialize = "IsStrPtrInitializedModel")]
    IsStrPtrInitialized,
    #[strum(serialize = "IsSliceChunkPtrInitializedModel")]
    IsSliceChunkPtrInitialized,
    #[strum(serialize = "IsSlicePtrInitializedModel")]
    IsSlicePtrInitialized,
    #[strum(serialize = "OffsetModel")]
    Offset,
    #[strum(serialize = "PtrOffsetFromModel")]
    PtrOffsetFrom,
    #[strum(serialize = "PtrOffsetFromUnsignedModel")]
    PtrOffsetFromUnsigned,
    #[strum(serialize = "RunContractModel")]
    RunContract,
    #[strum(serialize = "RunLoopContractModel")]
    RunLoopContract,
    #[strum(serialize = "SetPtrInitializedModel")]
    SetPtrInitialized,
    #[strum(serialize = "SetSliceChunkPtrInitializedModel")]
    SetSliceChunkPtrInitialized,
    #[strum(serialize = "SetSlicePtrInitializedModel")]
    SetSlicePtrInitialized,
    #[strum(serialize = "PanicStub")]
    PanicStub,
    #[strum(serialize = "SetStrPtrInitializedModel")]
    SetStrPtrInitialized,
    #[strum(serialize = "SimdBitmaskModel")]
    SimdBitmask,
    #[strum(serialize = "SizeOfDynObjectModel")]
    SizeOfDynObject,
    #[strum(serialize = "SizeOfSliceObjectModel")]
    SizeOfSliceObject,
    #[strum(serialize = "SizeOfValRawModel")]
    SizeOfVal,
    #[strum(serialize = "StoreArgumentModel")]
    StoreArgument,
    #[strum(serialize = "WriteAnySliceModel")]
    WriteAnySlice,
    #[strum(serialize = "WriteAnySlimModel")]
    WriteAnySlim,
    #[strum(serialize = "WriteAnyStrModel")]
    WriteAnyStr,
}

/// Kani hooks are Rust functions defined in the Kani library that exposes some semantics
/// from our solvers / symbolic execution engines.
///
/// Thus, they get handled by the codegen stage.
#[derive(Debug, Copy, Clone, Eq, PartialEq, IntoStaticStr, EnumIter, EnumString, Hash)]
pub enum KaniHook {
    #[strum(serialize = "AnyRawHook")]
    AnyRaw,
    #[strum(serialize = "AssertHook")]
    Assert,
    #[strum(serialize = "AssumeHook")]
    Assume,
    #[strum(serialize = "CheckHook")]
    Check,
    #[strum(serialize = "CoverHook")]
    Cover,
    #[strum(serialize = "ExistsHook")]
    Exists,
    #[strum(serialize = "ForallHook")]
    Forall,
    #[strum(serialize = "InitContractsHook")]
    InitContracts,
    #[strum(serialize = "IsAllocatedHook")]
    IsAllocated,
    /// Marks entry into the dynamic extent of a contract-checked function's
    /// modifies wrapper. The single argument is the `_wrapper_arg` tuple of
    /// `*const T` pointers declared by `#[kani::modifies(...)]` (FC-06).
    #[strum(serialize = "ModifiesFrameEnterHook")]
    ModifiesFrameEnter,
    /// Marks exit from the modifies wrapper's dynamic extent (FC-06).
    #[strum(serialize = "ModifiesFrameExitHook")]
    ModifiesFrameExit,
    #[strum(serialize = "PanicHook")]
    Panic,
    #[strum(serialize = "PointerObjectHook")]
    PointerObject,
    #[strum(serialize = "PointerOffsetHook")]
    PointerOffset,
    #[strum(serialize = "SafetyCheckHook")]
    SafetyCheck,
    #[strum(serialize = "SafetyCheckNoAssumeHook")]
    SafetyCheckNoAssume,
    #[strum(serialize = "UnsupportedCheckHook")]
    UnsupportedCheck,
    #[strum(serialize = "UntrackedDerefHook")]
    UntrackedDeref,
    /// Part of #1906: Value view for spec-level mathematical values.
    #[strum(serialize = "ValueViewHook")]
    ValueView,
}

impl From<KaniIntrinsic> for KaniFunction {
    fn from(value: KaniIntrinsic) -> Self {
        KaniFunction::Intrinsic(value)
    }
}

impl From<KaniModel> for KaniFunction {
    fn from(value: KaniModel) -> Self {
        KaniFunction::Model(value)
    }
}

impl From<KaniHook> for KaniFunction {
    fn from(value: KaniHook) -> Self {
        KaniFunction::Hook(value)
    }
}

/// Tries to get the [KaniFunction] from a given attribute string.
pub fn try_get_kani_function(fn_attr: &str) -> Option<KaniFunction> {
    if let Ok(intrinsic) = KaniIntrinsic::from_str(fn_attr) {
        Some(intrinsic.into())
    } else if let Ok(model) = KaniModel::from_str(fn_attr) {
        Some(model.into())
    } else if let Ok(hook) = KaniHook::from_str(fn_attr) {
        Some(hook.into())
    } else {
        None
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::str::FromStr;
    use strum::IntoEnumIterator;

    #[test]
    fn try_get_kani_function_recognizes_all_intrinsics() {
        for intrinsic in KaniIntrinsic::iter() {
            let name: &str = intrinsic.into();
            let result = try_get_kani_function(name);
            assert_eq!(
                result,
                Some(KaniFunction::Intrinsic(intrinsic)),
                "Intrinsic {name} not recognized"
            );
        }
    }

    #[test]
    fn try_get_kani_function_recognizes_all_models() {
        for model in KaniModel::iter() {
            let name: &str = model.into();
            let result = try_get_kani_function(name);
            assert_eq!(result, Some(KaniFunction::Model(model)), "Model {name} not recognized");
        }
    }

    #[test]
    fn try_get_kani_function_recognizes_all_hooks() {
        for hook in KaniHook::iter() {
            let name: &str = hook.into();
            let result = try_get_kani_function(name);
            assert_eq!(result, Some(KaniFunction::Hook(hook)), "Hook {name} not recognized");
        }
    }

    #[test]
    fn try_get_kani_function_returns_none_for_unknown() {
        assert_eq!(try_get_kani_function("UnknownFunction"), None);
        assert_eq!(try_get_kani_function(""), None);
        assert_eq!(try_get_kani_function("Assert"), None); // missing "Hook" suffix
        assert_eq!(try_get_kani_function("any_model"), None); // wrong case
    }

    #[test]
    fn intrinsic_strum_round_trip() {
        for intrinsic in KaniIntrinsic::iter() {
            let name: &str = intrinsic.into();
            let parsed = KaniIntrinsic::from_str(name).expect(name);
            assert_eq!(parsed, intrinsic, "Round-trip failed for {name}");
        }
    }

    #[test]
    fn model_strum_round_trip() {
        for model in KaniModel::iter() {
            let name: &str = model.into();
            let parsed = KaniModel::from_str(name).expect(name);
            assert_eq!(parsed, model, "Round-trip failed for {name}");
        }
    }

    #[test]
    fn hook_strum_round_trip() {
        for hook in KaniHook::iter() {
            let name: &str = hook.into();
            let parsed = KaniHook::from_str(name).expect(name);
            assert_eq!(parsed, hook, "Round-trip failed for {name}");
        }
    }

    #[test]
    fn from_intrinsic_wraps_correctly() {
        let func: KaniFunction = KaniIntrinsic::AnyModifies.into();
        assert_eq!(func, KaniFunction::Intrinsic(KaniIntrinsic::AnyModifies));
    }

    #[test]
    fn from_model_wraps_correctly() {
        let func: KaniFunction = KaniModel::Any.into();
        assert_eq!(func, KaniFunction::Model(KaniModel::Any));
    }

    #[test]
    fn from_hook_wraps_correctly() {
        let func: KaniFunction = KaniHook::Assert.into();
        assert_eq!(func, KaniFunction::Hook(KaniHook::Assert));
    }

    #[test]
    fn spot_check_well_known_intrinsics() {
        assert_eq!(
            try_get_kani_function("AnyModifiesIntrinsic"),
            Some(KaniFunction::Intrinsic(KaniIntrinsic::AnyModifies))
        );
        assert_eq!(
            try_get_kani_function("ValidValueIntrinsic"),
            Some(KaniFunction::Intrinsic(KaniIntrinsic::ValidValue))
        );
    }

    #[test]
    fn spot_check_well_known_models() {
        assert_eq!(try_get_kani_function("AnyModel"), Some(KaniFunction::Model(KaniModel::Any)));
        assert_eq!(
            try_get_kani_function("PanicStub"),
            Some(KaniFunction::Model(KaniModel::PanicStub))
        );
    }

    #[test]
    fn spot_check_well_known_hooks() {
        assert_eq!(try_get_kani_function("AssertHook"), Some(KaniFunction::Hook(KaniHook::Assert)));
        assert_eq!(try_get_kani_function("CoverHook"), Some(KaniFunction::Hook(KaniHook::Cover)));
    }

    #[test]
    fn intrinsic_variant_count() {
        assert_eq!(KaniIntrinsic::iter().count(), 8, "KaniIntrinsic variant count changed");
    }

    #[test]
    fn model_variant_count() {
        assert_eq!(KaniModel::iter().count(), 29, "KaniModel variant count changed");
    }

    #[test]
    fn hook_variant_count() {
        assert_eq!(KaniHook::iter().count(), 19, "KaniHook variant count changed");
    }
}
