// Copyright 2026 Andrew Yates
// SPDX-License-Identifier: Apache-2.0 OR MIT
// Author: Andrew Yates <andrewyates.name@gmail.com>

// Copyright Kani Contributors
// SPDX-License-Identifier: Apache-2.0 OR MIT
//! Represent information about an artifact type.

use std::ffi::OsStr;
use std::ops::Deref;
use std::path::{Path, PathBuf};

/// Represent the type of an artifact generated by trust_mc and the corresponding extension.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum ArtifactType {
    /// The metadata generated by the trust_mc compiler.
    Metadata,
    /// The compiler output file used as the base for artifact path computation.
    ///
    /// Originally named `SymTabGoto` in upstream Kani (CBMC symbol table goto binary).
    /// Renamed to `ModelBase` since trust_mc uses AY, not CBMC — the `.symtab.out` extension
    /// is retained for path compatibility with existing harness metadata.
    ModelBase,
    /// The verification condition artifact from trust_mc_core.
    /// Contains structured property metadata alongside `.smt2` files.
    VcArtifact,
}

impl ArtifactType {
    const fn extension(&self) -> &'static str {
        match self {
            ArtifactType::Metadata => "kani-metadata.json",
            ArtifactType::ModelBase => "symtab.out",
            ArtifactType::VcArtifact => "vc.json",
        }
    }
}

/// Create a new path by stripping the compound extension and attaching a new one.
///
/// All artifact types have compound extensions (e.g. `.symtab.out`, `.kani-metadata.json`).
/// This strips the outer extension pair and applies the target type's extension.
///
/// E.g.:
/// ```
/// # use std::path::PathBuf;
/// # use trust_mc_metadata::{ArtifactType, artifact::convert_type};
/// let path = PathBuf::from("my_file.symtab.out");
/// let vc = convert_type(&path, ArtifactType::VcArtifact);
/// assert_eq!(vc.as_os_str(), "my_file.vc.json");
/// ```
pub fn convert_type(path: &Path, to: ArtifactType) -> PathBuf {
    let mut result = path.to_path_buf();
    result.set_extension("");
    result.set_extension(to);
    result
}

impl AsRef<str> for ArtifactType {
    fn as_ref(&self) -> &str {
        self.extension()
    }
}

impl AsRef<OsStr> for ArtifactType {
    fn as_ref(&self) -> &OsStr {
        self.extension().as_ref()
    }
}

impl Deref for ArtifactType {
    type Target = str;

    fn deref(&self) -> &Self::Target {
        self.extension()
    }
}

#[cfg(test)]
mod test {
    use super::{ArtifactType::*, convert_type};
    use std::path::PathBuf;

    #[test]
    fn test_convert_ok() {
        let path = PathBuf::from("/tmp/my_file.rs").with_extension(ModelBase);
        let vc = convert_type(&path, VcArtifact);
        assert_eq!(vc.as_os_str(), "/tmp/my_file.vc.json");

        let metadata = convert_type(&path, Metadata);
        assert_eq!(metadata.as_os_str(), "/tmp/my_file.kani-metadata.json");
    }

    #[test]
    fn test_set_extension_ok() {
        let path = PathBuf::from("/tmp/my_file.rs").with_extension(ModelBase);
        assert_eq!(path.as_os_str(), "/tmp/my_file.symtab.out");
    }
}
