#!/usr/bin/env python3
# Copyright 2026 Andrew Yates
# SPDX-License-Identifier: Apache-2.0 OR MIT
# Author: Andrew Yates <andrewyates.name@gmail.com>

"""Extract fully-qualified #[kani::proof] harness names from a Rust file.

Supports three sources:

1. Plain ``#[kani::proof] fn name()`` declarations.
2. ``#[cfg_attr(kani, kani::proof)] fn name()`` declarations.
3. ``macro_rules!`` bodies that emit ``#[kani::proof]`` harnesses, together
   with their call sites. Without this, files like
   ``tests/zani/Arbitrary/nonzero.rs`` (12 harnesses generated by
   ``harness!(...)``) are silently dropped by the compiletest driver.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path


ATTR_BODY = re.compile(r"^\s*#\[\s*(.*?)\s*\]\s*(?://.*)?$")
KANI_PROOF_META = re.compile(r"^kani::proof(?:\s*$|\s*\(.*\)\s*$)")
KANI_PROOF_FOR_CONTRACT_META = re.compile(
    r"^kani::proof_for_contract\s*\(.*\)\s*$"
)
FN_DECL = re.compile(
    r"^\s*(?:(?:pub(?:\([^)]*\))?\s+|unsafe\s+|async\s+|const\s+)*)fn\s+([A-Za-z0-9_]+)\s*\("
)
MOD_DECL = re.compile(r"^\s*(?:pub(?:\([^)]*\))?\s+)?mod\s+([A-Za-z0-9_]+)\s*\{")

# `macro_rules! <name> { ... }` declaration.
MACRO_RULES_DECL = re.compile(r"^\s*macro_rules!\s+([A-Za-z0-9_]+)\s*\{")
# `$<param_name>: <fragment_spec>` — ident/tt/ty/expr/...
MACRO_PARAM = re.compile(r"\$([A-Za-z_][A-Za-z0-9_]*)\s*:\s*([A-Za-z_]+)")
# `fn $<param>(` template used to declare the harness function inside a macro arm.
MACRO_FN_TEMPLATE = re.compile(r"\bfn\s+\$([A-Za-z_][A-Za-z0-9_]*)\s*\(")
# Macro call site opener: `<name>!(` or `<name>!{` or `<name>![`.
MACRO_CALL = re.compile(r"^\s*([A-Za-z_][A-Za-z0-9_]*)\s*!\s*[\(\{\[]")
# Bare identifier predicate for macro-call arguments.
IDENT_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def _strip_string_and_comment(line: str) -> str:
    """Remove string literals and ``//`` comments so brace counts are accurate."""
    line = re.sub(r'"(?:[^"\\]|\\.)*"', "", line)
    line = re.sub(r"//.*$", "", line)
    return line


def _find_macro_proof_emitters(lines: list[str]) -> dict[str, list[int]]:
    """Return ``{macro_name: [param_index, ...]}`` for proof-emitting arms.

    ``param_index`` is the 0-based position of the ``$ident``-bound macro
    parameter that becomes the harness function name inside the arm body.
    Multiple arms of the same macro can yield multiple entries; duplicate
    indices are preserved so later dedup happens naturally on call-site names.

    An arm qualifies iff its body contains ``#[kani::proof]`` (or the
    ``cfg_attr(kani, kani::proof)`` form) and a ``fn $<ident>(`` template
    whose parameter is ident-bound in the arm's parameter list.
    """
    emitters: dict[str, list[int]] = {}

    i = 0
    while i < len(lines):
        decl = MACRO_RULES_DECL.match(lines[i])
        if not decl:
            i += 1
            continue

        macro_name = decl.group(1)
        # Brace-match from the opening `{` on the declaration line.
        first = _strip_string_and_comment(lines[i])
        depth = first.count("{") - first.count("}")
        body_start = i
        j = i + 1
        while j < len(lines) and depth > 0:
            stripped = _strip_string_and_comment(lines[j])
            depth += stripped.count("{") - stripped.count("}")
            j += 1
        body_end = j  # exclusive
        body_text = "\n".join(lines[body_start:body_end])

        # Strip the `macro_rules! name {` prefix and trailing `}` to get arms.
        inner = body_text
        brace_pos = inner.find("{")
        if brace_pos != -1:
            inner = inner[brace_pos + 1 :]
        last_close = inner.rfind("}")
        if last_close != -1:
            inner = inner[:last_close]

        for params, body in _parse_arms(inner):
            if "kani::proof" not in body:
                continue
            param_list = [m.group(1) for m in MACRO_PARAM.finditer(params)]
            # Find each `fn $<ident>(` in the arm body. Accept the first one
            # whose enclosing scope (since the last `}`) contains a proof
            # attribute. This avoids mis-attributing the harness name to a
            # preceding `pub fn $stub(...)` helper defined in the same arm.
            for tmpl_match in MACRO_FN_TEMPLATE.finditer(body):
                prefix = body[: tmpl_match.start()]
                last_brace = prefix.rfind("}")
                scoped_prefix = prefix[last_brace + 1 :] if last_brace != -1 else prefix
                if "kani::proof" not in scoped_prefix:
                    continue
                fn_param_name = tmpl_match.group(1)
                if fn_param_name not in param_list:
                    continue
                idx = param_list.index(fn_param_name)
                emitters.setdefault(macro_name, []).append(idx)
                break

        i = body_end if body_end > i else i + 1

    return emitters


_MATCHING_CLOSER = {"(": ")", "[": "]", "{": "}"}


def _match_balanced(text: str, pos: int) -> tuple[int, int] | None:
    """Return ``(inner_start, close_pos)`` for a balanced delimiter group.

    ``text[pos]`` must be one of ``(``, ``[``, or ``{``. The returned
    ``inner_start`` is ``pos + 1`` and ``close_pos`` is the index of the
    matching closer. Returns ``None`` on imbalance.
    """
    if pos >= len(text) or text[pos] not in _MATCHING_CLOSER:
        return None
    opener = text[pos]
    closer = _MATCHING_CLOSER[opener]
    depth = 1
    k = pos + 1
    start = k
    while k < len(text):
        ch = text[k]
        if ch == opener:
            depth += 1
        elif ch == closer:
            depth -= 1
            if depth == 0:
                return (start, k)
        k += 1
    return None


def _skip_ws(text: str, pos: int) -> int:
    while pos < len(text) and text[pos].isspace():
        pos += 1
    return pos


def _parse_arms(inner: str) -> list[tuple[str, str]]:
    """Split a ``macro_rules!`` body into ``(param_text, body_text)`` per arm.

    ``inner`` is the content between the outermost ``{`` and ``}`` of the
    ``macro_rules!`` declaration. Arms look like ``( ... ) => { ... };``.
    We honor paren, brace, and bracket depth so nested delimiters inside arm
    bodies cannot confuse the split.
    """
    arms: list[tuple[str, str]] = []

    pos = 0
    n = len(inner)
    while pos < n:
        pos = _skip_ws(inner, pos)
        if pos >= n:
            break
        if inner[pos] not in _MATCHING_CLOSER:
            pos += 1
            continue

        params_span = _match_balanced(inner, pos)
        if params_span is None:
            break
        params = inner[params_span[0] : params_span[1]]
        pos = params_span[1] + 1

        pos = _skip_ws(inner, pos)
        if inner[pos : pos + 2] != "=>":
            continue
        pos = _skip_ws(inner, pos + 2)

        body_span = _match_balanced(inner, pos) if pos < n else None
        if body_span is None:
            break
        body = inner[body_span[0] : body_span[1]]
        pos = body_span[1] + 1

        arms.append((params, body))

        # Skip optional inter-arm whitespace and separator `;`.
        while pos < n and inner[pos] in " \t\r\n;":
            pos += 1

    return arms


def _split_top_level_commas(text: str) -> list[str]:
    """Split ``text`` on top-level commas.

    Honors nested ``()``, ``[]``, ``{}``, and ``<>`` so generics in ``$ty``
    positions and nested attribute arguments don't fragment the split.
    """
    out: list[str] = []
    depth = 0
    current: list[str] = []
    for ch in text:
        if ch in "([{<":
            depth += 1
            current.append(ch)
        elif ch in ")]}>":
            depth = max(0, depth - 1)
            current.append(ch)
        elif ch == "," and depth == 0:
            out.append("".join(current).strip())
            current = []
        else:
            current.append(ch)
    tail = "".join(current).strip()
    if tail:
        out.append(tail)
    return out


def _split_macro_args(args: str) -> list[str]:
    """Split a macro call-site argument list on top-level commas."""
    return _split_top_level_commas(args)


def _extract_macro_call_args(line: str, bang_index: int) -> str | None:
    """Return the argument text inside a single-line macro call.

    ``bang_index`` points at the ``!`` after the macro name. Returns ``None``
    if delimiters don't balance on this line.
    """
    k = bang_index
    while k < len(line) and line[k] not in _MATCHING_CLOSER:
        k += 1
    span = _match_balanced(line, k) if k < len(line) else None
    if span is None:
        return None
    return line[span[0] : span[1]]


def _qualify(name: str, mod_stack: list[tuple[str, int]]) -> str:
    if not mod_stack:
        return name
    return "::".join(n for n, _ in mod_stack) + "::" + name


def _update_mod_stack(
    line: str,
    stripped: str,
    mod_stack: list[tuple[str, int]],
    brace_depth: int,
) -> int:
    """Push/pop ``mod_stack`` based on this line and return new ``brace_depth``."""
    mod_match = MOD_DECL.match(line)
    if mod_match:
        mod_stack.append((mod_match.group(1), brace_depth))
    brace_depth += stripped.count("{") - stripped.count("}")
    while mod_stack and brace_depth <= mod_stack[-1][1]:
        mod_stack.pop()
    return brace_depth


def _expand_macro_call(
    line: str,
    macro_emitters: dict[str, list[int]],
    mod_stack: list[tuple[str, int]],
) -> list[str]:
    """Return harness names produced by a single-line macro-call on ``line``.

    Returns an empty list if the line does not call a proof-emitting macro or
    if the call's delimiters are imbalanced.
    """
    call_match = MACRO_CALL.match(line)
    if not call_match or call_match.group(1) not in macro_emitters:
        return []
    macro_name = call_match.group(1)
    bang_idx = line.index("!", call_match.start(1))
    args_text = _extract_macro_call_args(line, bang_idx)
    if args_text is None:
        return []
    args = _split_macro_args(args_text)
    out: list[str] = []
    for idx in macro_emitters[macro_name]:
        if idx < len(args):
            ident = args[idx].strip()
            if IDENT_RE.match(ident):
                out.append(_qualify(ident, mod_stack))
    return out


def _is_skippable_between_attr_and_fn(line: str) -> bool:
    return bool(re.match(r"^\s*(#\[|//|/\*|\*|\*/)", line)) or line.strip() == ""


def _is_kani_harness_meta(meta: str) -> bool:
    meta = meta.strip()
    return bool(
        KANI_PROOF_META.match(meta)
        or KANI_PROOF_FOR_CONTRACT_META.match(meta)
    )


def _meta_call_args(meta: str, name: str) -> list[str] | None:
    prefix = re.match(rf"^{re.escape(name)}\s*", meta)
    if not prefix:
        return None
    open_pos = _skip_ws(meta, prefix.end())
    span = _match_balanced(meta, open_pos)
    if span is None or meta[span[1] + 1 :].strip():
        return None
    return _split_top_level_commas(meta[span[0] : span[1]])


def _is_cfg_attr_kani_harness(meta: str) -> bool:
    args = _meta_call_args(meta, "cfg_attr")
    if args is None:
        return False
    if len(args) < 2 or args[0].strip() != "kani":
        return False
    return any(_is_kani_harness_meta(arg) for arg in args[1:])


def _cfg_expr_active_by_default(expr: str) -> bool:
    expr = expr.strip()
    if expr == "kani":
        return True

    all_args = _meta_call_args(expr, "all")
    if all_args is not None:
        return all(_cfg_expr_active_by_default(arg) for arg in all_args)

    any_args = _meta_call_args(expr, "any")
    if any_args is not None:
        return any(_cfg_expr_active_by_default(arg) for arg in any_args)

    not_args = _meta_call_args(expr, "not")
    if not_args is not None:
        return len(not_args) == 1 and not _cfg_expr_active_by_default(not_args[0])

    return False


def _is_inactive_cfg_meta(meta: str) -> bool:
    args = _meta_call_args(meta.strip(), "cfg")
    return (
        args is not None
        and len(args) == 1
        and not _cfg_expr_active_by_default(args[0])
    )


def _attr_meta(line: str) -> str | None:
    attr = ATTR_BODY.match(line)
    if not attr:
        return None
    return attr.group(1).strip()


def _apply_attr_meta(
    meta: str,
    *,
    want_fn: bool,
    want_fn_blocked: bool,
    pending_inactive_cfg: bool,
) -> tuple[bool, bool, bool]:
    if _is_inactive_cfg_meta(meta):
        pending_inactive_cfg = True
        want_fn_blocked = want_fn_blocked or want_fn
    if _is_kani_harness_meta(meta) or _is_cfg_attr_kani_harness(meta):
        want_fn = True
        want_fn_blocked = want_fn_blocked or pending_inactive_cfg
    return want_fn, want_fn_blocked, pending_inactive_cfg


def _append_macro_expansions(
    line: str,
    *,
    macro_emitters: dict[str, list[int]],
    mod_stack: list[tuple[str, int]],
    harnesses: list[str],
    pending_inactive_cfg: bool,
) -> bool:
    if not macro_emitters:
        return pending_inactive_cfg
    expanded = _expand_macro_call(line, macro_emitters, mod_stack)
    if not expanded:
        return pending_inactive_cfg
    if not pending_inactive_cfg:
        harnesses.extend(expanded)
    return False


def extract_proof_harnesses(path: Path) -> list[str]:
    lines = path.read_text(encoding="utf-8").splitlines()
    macro_emitters = _find_macro_proof_emitters(lines)

    mod_stack: list[tuple[str, int]] = []
    brace_depth = 0
    harnesses: list[str] = []
    want_fn = False
    want_fn_blocked = False
    pending_inactive_cfg = False

    for line in lines:
        stripped = _strip_string_and_comment(line)
        brace_depth = _update_mod_stack(line, stripped, mod_stack, brace_depth)

        meta = _attr_meta(line)
        if meta is not None:
            want_fn, want_fn_blocked, pending_inactive_cfg = _apply_attr_meta(
                meta,
                want_fn=want_fn,
                want_fn_blocked=want_fn_blocked,
                pending_inactive_cfg=pending_inactive_cfg,
            )
            continue

        pending_inactive_cfg = _append_macro_expansions(
            line,
            macro_emitters=macro_emitters,
            mod_stack=mod_stack,
            harnesses=harnesses,
            pending_inactive_cfg=pending_inactive_cfg,
        )

        if not want_fn:
            if not _is_skippable_between_attr_and_fn(line):
                pending_inactive_cfg = False
            continue
        if _is_skippable_between_attr_and_fn(line):
            continue

        fn_match = FN_DECL.match(line)
        if fn_match and not want_fn_blocked:
            harnesses.append(_qualify(fn_match.group(1), mod_stack))
        want_fn = False
        want_fn_blocked = False
        pending_inactive_cfg = False

    return sorted(set(harnesses))


def _run_self_tests() -> int:
    # Defer import so a malformed test harness never breaks the main extractor.
    from extract_proof_harnesses_tests import run

    return run()


def main() -> int:
    if len(sys.argv) == 2 and sys.argv[1] == "--self-test":
        return _run_self_tests()

    if len(sys.argv) != 2:
        sys.stderr.write("usage: extract_proof_harnesses.py <rust-file>\n")
        sys.stderr.write("       extract_proof_harnesses.py --self-test\n")
        return 2

    for harness in extract_proof_harnesses(Path(sys.argv[1])):
        sys.stdout.write(f"{harness}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
