// Copyright 2026 Andrew Yates
// SPDX-License-Identifier: Apache-2.0 OR MIT
// Author: Andrew Yates <andrewyates.name@gmail.com>

// Copyright Kani Contributors
// SPDX-License-Identifier: Apache-2.0 OR MIT
//! This module defines the structure for a Kani project.
//! The goal is to provide one project view independent on the build system (cargo / standalone
//! rustc) and its configuration (e.g.: linker type).

use crate::call_single_file::LibConfig;
use crate::metadata::from_json;
use crate::session::{KaniSession, lib_folder};
use crate::util::args::{CommandWrapper, PassTo, RustcArg, encode_as_rustc_arg};
use crate::util::{apply_rust_min_stack, crate_name, info_operation};
use anyhow::{Context, Result};
use std::env::current_dir;
use std::fs;
use std::ops::Deref;
use std::path::{Path, PathBuf};
use std::process::Command;
use tracing::debug;
use trust_mc_metadata::{ArtifactType, HarnessMetadata, KaniMetadata};

/// This structure represent the project information relevant for verification.
/// A `Project` contains information about all crates under verification, as well as all
/// artifacts relevant for verification.
///
/// For one specific harness, there should be up to one artifact of each type. I.e., artifacts of
/// the same type are linked as part of creating the project.
///
/// However, one artifact can be used for multiple harnesses. This will depend on the type of
/// artifact, but it should be transparent for the user of this object.
#[derive(Debug, Default)]
pub(crate) struct Project {
    /// Each target crate metadata.
    pub metadata: Vec<KaniMetadata>,
    /// The directory where all outputs should be directed to. This path represents the canonical
    /// version of outdir.
    pub outdir: PathBuf,
    /// The path to the input file the project was built from.
    /// Note that it will only be `Some(...)` if this was built from a standalone project.
    pub input: Option<PathBuf>,
    /// The collection of artifacts kept as part of this project.
    artifacts: Vec<Artifact>,
    /// Records the cargo metadata from the build, if there was any
    pub cargo_metadata: Option<cargo_metadata::Metadata>,
}

impl Project {
    /// Get all harnesses from a project. This will include all test and proof harnesses.
    /// We could create a `get_proof_harnesses` and a `get_tests_harnesses` later if we see the
    /// need to split them.
    pub(crate) fn get_all_harnesses(&self) -> Vec<&HarnessMetadata> {
        self.metadata
            .iter()
            .flat_map(|crate_metadata| {
                crate_metadata.proof_harnesses.iter().chain(crate_metadata.test_harnesses.iter())
            })
            .collect()
    }

    /// Try to build a new project from the build result metadata.
    ///
    /// This method will parse the metadata in order to gather all artifacts generated by the
    /// compiler.
    fn try_new(
        outdir: PathBuf,
        input: Option<PathBuf>,
        metadata: Vec<KaniMetadata>,
        cargo_metadata: Option<cargo_metadata::Metadata>,
    ) -> Result<Self> {
        // AY backend produces .smt2 files directly and doesn't need goto linking
        // or artifact tracking. The harness_runner constructs paths from harness
        // metadata directly.
        let artifacts = vec![];

        Ok(Project { metadata, outdir, input, artifacts, cargo_metadata })
    }
}

/// Information about a build artifact.
#[derive(Debug, Eq, PartialEq, Clone, Hash)]
pub(crate) struct Artifact {
    /// The path for this artifact in the canonical form.
    path: PathBuf,
    /// The type of artifact.
    typ: ArtifactType,
}

impl AsRef<Path> for Artifact {
    fn as_ref(&self) -> &Path {
        self.path.as_ref()
    }
}

impl Deref for Artifact {
    type Target = Path;
    fn deref(&self) -> &Self::Target {
        &self.path
    }
}

impl Artifact {
    /// Create a new artifact if the given path exists.
    pub(crate) fn try_new(path: &Path, typ: ArtifactType) -> Result<Self> {
        Ok(Artifact {
            path: path.canonicalize().context(format!("Failed to process {}", path.display()))?,
            typ,
        })
    }
}

/// Generate a project using `cargo`.
/// Accept a boolean to build as many targets as possible. The number of failures in that case can
/// be collected from the project.
pub(crate) fn cargo_project(session: &mut KaniSession, keep_going: bool) -> Result<Project> {
    let outputs = session.cargo_build(keep_going)?;
    if session.args.no_codegen {
        info_operation(
            "info:",
            "Compilation succeeded up until codegen. Skipping codegen because of `--no-codegen` option. Rerun without `--no-codegen` to perform codegen.",
        );
        return Ok(Project::default());
    }
    let outdir = outputs.outdir.canonicalize()?;
    // For the MIR Linker we know there is only one metadata per crate. Use that in our favor.
    let metadata =
        outputs.metadata.iter().map(|md_file| from_json(md_file)).collect::<Result<Vec<_>>>()?;
    Project::try_new(outdir, None, metadata, Some(outputs.cargo_metadata))
}

/// Generate a project directly using `kani-compiler` on a single crate.
pub(crate) fn standalone_project(
    input: &Path,
    crate_name: Option<String>,
    session: &KaniSession,
) -> Result<Project> {
    StandaloneProjectBuilder::try_new(input, crate_name, session)?.build()
}

/// Builder for a standalone project.
struct StandaloneProjectBuilder<'a> {
    /// The directory where all outputs should be directed to.
    outdir: PathBuf,
    /// The metadata file for the target crate.
    metadata: Artifact,
    /// The input file.
    input: PathBuf,
    /// The crate name.
    crate_name: String,
    /// The Kani session.
    session: &'a KaniSession,
}

impl<'a> StandaloneProjectBuilder<'a> {
    /// Create a `StandaloneProjectBuilder` from the given input and session.
    /// This will perform a few validations before the build.
    fn try_new(input: &Path, krate_name: Option<String>, session: &'a KaniSession) -> Result<Self> {
        // Ensure the directory exist and it's in its canonical form.
        let outdir = if let Some(target_dir) = &session.args.target_dir {
            std::fs::create_dir_all(target_dir)?; // This is a no-op if directory exists.
            target_dir.canonicalize()?
        } else {
            input
                .canonicalize()
                .context("Failed to canonicalize input path")?
                .parent()
                .context("Input path has no parent directory")?
                .to_path_buf()
        };
        let crate_name = if let Some(name) = krate_name { name } else { crate_name(input)? };
        let metadata = standalone_artifact(&outdir, &crate_name, ArtifactType::Metadata);
        Ok(StandaloneProjectBuilder {
            outdir,
            metadata,
            input: input.to_path_buf(),
            crate_name,
            session,
        })
    }

    /// Build a project by compiling `self.input` file.
    fn build(self) -> Result<Project> {
        // Register artifacts that may be generated by the compiler / linker for future deletion.
        let rlib_path = self.rlib_name()?;
        self.session.record_temporary_file(&rlib_path);
        self.session.record_temporary_file(&self.metadata.path);

        // Residual-775 Wall-1 P5.2 (timing-only): arm the watchdog's
        // per-extra-harness extension BEFORE codegen. Codegen cost is
        // per-harness (compiler_interface iterates `unit.harnesses`), so an
        // N-harness file must finish N codegens — with only the post-codegen
        // extension (main.rs, after `determine_targets`) a slow-but-finite
        // multi-harness file was hard-killed inside the single-harness
        // budget (DriverTimeout). The count comes from the same source scan
        // the outer runners use for THEIR budget
        // (tools/kani-domination discover.rs: `#[kani::proof` matches), so
        // this never exceeds their allowance and the watchdog still fires
        // first, with honest UNKNOWN markers. The extension is idempotent;
        // the post-codegen call tops up any undercount from the
        // authoritative metadata. Cannot mint a false Safe: verdicts still
        // come from the solver and the demotion nets.
        crate::wall_clock_watchdog::extend_for_extra_harnesses(
            self.session.args.harness_timeout.map(std::time::Duration::from),
            scan_harness_count(&self.input),
        );

        // Build and link the artifacts.
        debug!(krate=?self.crate_name, input=?self.input, ?rlib_path, "build compile");
        self.compile()?;

        let metadata = from_json(&self.metadata)?;

        // Create the project with the artifacts built by the compiler.
        let result = Project::try_new(self.outdir, Some(self.input), vec![metadata], None);
        if let Ok(project) = &result {
            self.session.record_temporary_files(&project.artifacts);
        }
        result
    }

    /// Build the rlib name from the crate name.
    /// This is only used by 'kani', never 'cargo-kani', so we hopefully don't have too many corner
    /// cases to deal with.
    fn rlib_name(&self) -> Result<PathBuf> {
        let file_name = self.input.file_name().context("Input path has no file name")?;
        let path = self.outdir.join(file_name);
        let basedir = path.parent().unwrap_or(Path::new("."));
        let rlib_name = format!("lib{}.rlib", self.crate_name);

        Ok(basedir.join(rlib_name))
    }

    /// Compile the input Rust file into artifacts.
    ///
    /// This was moved from `KaniSession::compile_single_rust_file` to be part of the builder
    /// pattern, as it's only used by standalone projects (#957).
    fn compile(&self) -> Result<()> {
        let mut kani_args = self.session.kani_compiler_local_flags();
        kani_args.push(format!("--reachability={}", self.session.reachability_mode()).into());

        let lib_path = lib_folder().context("Failed to locate Kani library folder")?;
        let mut rustc_args = self.session.kani_rustc_flags(LibConfig::new(lib_path)?);
        rustc_args.push((&self.input).into());
        rustc_args.push("--out-dir".into());
        rustc_args.push(RustcArg::from(self.outdir.as_os_str()));
        rustc_args.push("--crate-name".into());
        rustc_args.push((&self.crate_name).into());

        if self.session.args.tests {
            // e.g. `tests/kani/Options/check_tests.rs` will fail because it already has it
            // so this is a hacky workaround
            let t = "--test".into();
            if !rustc_args.contains(&t) {
                rustc_args.push(t);
            }
        } else {
            // We only run against proof harnesses, so always compile as a library.
            // This ensures compilation passes if the crate does not have a `main` function.
            rustc_args.push("--crate-type".into());
            rustc_args.push("lib".into());
        }

        // Note that the order of arguments is important. Kani specific flags should precede
        // rustc ones.
        let mut cmd = Command::new(&self.session.kani_compiler);

        cmd.pass_rustc_arg(encode_as_rustc_arg(&kani_args), PassTo::OnlyLocalCrate)
            .pass_rustc_args(&rustc_args, PassTo::OnlyLocalCrate);

        // This is only required for stable but is a no-op for nightly channels
        cmd.env("RUSTC_BOOTSTRAP", "1");
        cmd.env("RUST_BACKTRACE", "1");

        // Ensure compiler has enough stack for complex MIR patterns (#1572).
        apply_rust_min_stack(&mut cmd);

        // Use timeout protection to prevent runaway compiler processes (#995)
        if self.session.args.common_args.quiet {
            self.session.run_suppress_with_tool_timeout(cmd)?;
        } else {
            self.session.run_terminal_with_tool_timeout(cmd)?;
        }
        Ok(())
    }
}

/// Pre-codegen harness-count estimate for a standalone input file (P5.2).
///
/// Counts `#[kani::proof` attribute occurrences — deliberately the EXACT
/// counting rule of the outer runners' budget scan
/// (`tools/kani-domination/src/discover.rs`), so the driver's extended
/// watchdog budget can never exceed the outer allowance derived from the
/// same file (the driver must always fire first, with honest markers,
/// before an outer SIGKILL). Undercounts (macro-generated harnesses,
/// `#[kani::harness]` spellings) are topped up post-codegen from the
/// compiler metadata. Unreadable input counts as 1 (no extension).
fn scan_harness_count(input: &Path) -> usize {
    std::fs::read_to_string(input).map(|src| src.matches("#[kani::proof").count()).unwrap_or(1)
}

/// Generate the expected path of a standalone artifact of the given type.
// Note: `out_dir` is already on canonical form, so no need to invoke `try_new()`.
fn standalone_artifact(out_dir: &Path, crate_name: &str, typ: ArtifactType) -> Artifact {
    let mut path = out_dir.join(crate_name);
    let _ = path.set_extension(typ);
    Artifact { path, typ }
}

/// Verify the custom version of the standard library in the given path.
///
/// Note that we assume that `std_path` points to a directory named "library".
/// This should be checked as part of the argument validation.
pub(crate) fn std_project(std_path: &Path, session: &KaniSession) -> Result<Project> {
    // Create output directory
    let outdir = if let Some(target_dir) = &session.args.target_dir {
        target_dir.clone()
    } else {
        current_dir()?.join("target")
    };
    fs::create_dir_all(&outdir)?; // This is a no-op if directory exists.
    let outdir = outdir.canonicalize()?;

    // Create dummy crate needed to build using `cargo -Z build-std`
    let dummy_crate = outdir.join("kani_verify_std");
    if dummy_crate.exists() {
        fs::remove_dir_all(&dummy_crate)?;
    }
    session.cargo_init_lib(&dummy_crate)?;

    // Build cargo project for dummy crate.
    let std_path = std_path.canonicalize()?;
    let std_parent = std_path.parent().context("std_path has no parent directory")?;
    let outputs = session.cargo_build_std(std_parent, &dummy_crate)?;

    // Get the metadata and return a Kani project.
    let metadata = outputs.iter().map(|md_file| from_json(md_file)).collect::<Result<Vec<_>>>()?;
    Project::try_new(outdir, None, metadata, None)
}
